In [1]:
import numpy as np
a = np.array([8,12,3])
print(a)
print (a[0])

[ 8 12  3]
8


In [2]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [3]:
import numpy as np

print(np.__version__)

1.19.2


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])


7


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [38]:
a[-1]

array([3, 4])

In [14]:
import numpy as np 
a = np.array([5,6,9], dtype = complex) 
print(a)

[5.+0.j 6.+0.j 9.+0.j]


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [16]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [17]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [20]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [22]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))


[0 1 2 3]


In [23]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [29]:
a = np.array([[0, 2], [3, 4],[5,7]]) 
a.ravel()

array([0, 2, 3, 4, 5, 7])

In [30]:
a.min()

0

In [31]:
a.max()

7

In [32]:
a.sum()

21

In [33]:
np.sqrt(a)

array([[0.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.64575131]])

In [34]:
a = np.array([[1, 2], [3, 4]])
b=np.array([[5,6],[7,8]])

In [35]:
a+b

array([[ 6,  8],
       [10, 12]])

In [36]:
a*b

array([[ 5, 12],
       [21, 32]])

In [37]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [39]:
a = np.array([[1, 2,6], [3, 4,9],[5,6,8]]) 
print(a)

[[1 2 6]
 [3 4 9]
 [5 6 8]]


In [40]:
a[0:2,2]


array([6, 9])

In [41]:
a[-1,0:2]

array([5, 6])

In [42]:
for cell in a.flat:
    print(cell)

1
2
6
3
4
9
5
6
8


In [47]:
a=np.arange(6).reshape(3,2)
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [45]:
b=np.arange(6,12).reshape(3,2)

In [48]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [49]:
a=np.arange(30).reshape(2,15)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
